[unstable]
build-std = ["core", "compiler_builtins"]

[build]
target = "riscv64gc-unknown-none-elf"
rustflags = ["-Clink-arg=-Tsrc/kernel.ld"]

[target.riscv64gc-unknown-none-elf]
runner = "qemu-system-riscv64 -machine virt -cpu rv64 -m 128M -bios none -nographic -serial mon:stdio -s -kernel "
